Aplikacja webowa do zarządzania zespołami/Pages/ActiveGroup.cshtml.cs
using Aplikacja_webowa_do_zarządzania_zespołami.Models;
using Aplikacja_webowa_do_zarządzania_zespołami.DTO_models_and_static_vars;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Aplikacja_webowa_do_zarządzania_zespołami.DAO;
using Aplikacja_webowa_do_zarządzania_zespołami.PartialModels;

namespace Aplikacja_webowa_do_zarządzania_zespołami.Pages
{
    public class GroupsModel : PageModel
    {
        private readonly IGroupDAO _groupDAO;
        public GroupsModel(IGroupDAO groupDAO)
        {
            _groupDAO = groupDAO;
            groupList = new List<ActiveGroupDTO>();
        }

        public List<ActiveGroupDTO> groupList;
        public string data;
        public int? userId;
        public int? groupId;
        public string username;
        public string activeGroup;

        [BindProperty(SupportsGet = true)]
        public int changeGroupId { get; set; }

        //OnGet and OnPost methods
        public void OnGet()
        {
            //Read session data
            data = HttpContext.Session.GetString(ConstVariables.GetKeyValue(1));
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            username = HttpContext.Session.GetString(ConstVariables.GetKeyValue(4));

            try
            {
                groupList = _groupDAO.GetGroupsForActiveUser((int)userId);
                activeGroup = _groupDAO.GetGroupName((int)groupId);
            }
            catch
            {
                Page();
            }
        }

        public IActionResult OnPostChangeActiveGroup()
        {
            //I need to get values again this time for Post request
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));

            //Check if someone doesn't replaced id with some other id that is not in groupList
            if (_groupDAO.IsUserActiveMemberOfSelectedGroup(userId,changeGroupId))
            {
                //Check if user is an owner
                if(_groupDAO.IsUserAnOwnerOfSelectedGroup(userId,changeGroupId))
                {
                    HttpContext.Session.SetString(ConstVariables.GetKeyValue(1), "Owner");
                }
                else
                {
                    HttpContext.Session.SetString(ConstVariables.GetKeyValue(1), "User");
                }
                HttpContext.Session.SetInt32(ConstVariables.GetKeyValue(3), changeGroupId);
            }

            return RedirectToPage("ActiveGroup");
        }
    }
}

Aplikacja webowa do zarządzania zespołami/Pages/AdminTasks.cshtml.cs
using Aplikacja_webowa_do_zarządzania_zespołami.Models;
using Aplikacja_webowa_do_zarządzania_zespołami.DTO_models_and_static_vars;
using Aplikacja_webowa_do_zarządzania_zespołami.Validation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Aplikacja_webowa_do_zarządzania_zespołami.Pages
{
    public class AdminTasksModel : PageModel
    {
        private readonly DatabaseContext _dbContext;

        public AdminTasksModel(DatabaseContext dbContext)
        {
            _dbContext = dbContext;
            tasksList = new List<Models.Task>();
            userList = new List<Models.User>();
        }

        public List<Models.Task> tasksList;
        public List<Models.User> userList;
        private string error ="";
        public string data;
        public int? userId;
        public int? groupId;
        public string? username;

        [BindProperty(SupportsGet = true)]
        public Models.Task createOrEditTask { get; set; }

        [BindProperty(SupportsGet = true)]
        public int deleteTask { get; set; }

        private Models.Task CreateEmptyTask(int id)
        {
            Models.Task emptyTask = new Models.Task();
            emptyTask.start_date = DateTime.Now;
            emptyTask.end_date = DateTime.Now;
            emptyTask.task_id = id;
            emptyTask.task_name = "Błąd";
            emptyTask.description = "Nie znaleziono w bazie określonego zadania";
            emptyTask.status = "Błąd";
            emptyTask.priority = "Błąd";

            return emptyTask;
        }

        private void EditTask(Models.Task task)
        {
            //Now lets get original task and change values aside from task_id, group_id, user_id, and feedback
            //if status changed from nieukończone to ukończone then add finish_date
            Models.Task originalTask = _dbContext.Tasks.Where(t => t.task_id == task.task_id).First();
            if (originalTask.status == "nieukończone" && createOrEditTask.status == "ukończone")
            {
                //Setting a date on now and setting seconds to 0
                originalTask.finish_date = DateTime.Now.AddSeconds(-DateTime.Now.Second);
            }
            originalTask.task_name = task.task_name;
            originalTask.users_user_id = task.users_user_id;
            originalTask.description = task.description;
            originalTask.start_date = task.start_date;
            originalTask.end_date = task.end_date;
            originalTask.status = task.status;
            originalTask.priority = task.priority;
            _dbContext.Update(originalTask);
            _dbContext.SaveChanges();
        }

        private string IsEndDateHigherThanStartDate(DateTime startDate, DateTime endDate)
        {
            if (endDate < startDate)
                return "Data początku musi być mniejsza od daty końca";

            return "";
        }

        //OnGet and OnPost methods
        public void OnGet()
        {
            data = HttpContext.Session.GetString(ConstVariables.GetKeyValue(1));
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            username = HttpContext.Session.GetString(ConstVariables.GetKeyValue(4));

            tasksList = _dbContext.Tasks.Where(t => t.groups_group_id == groupId).ToList();

            //Find all users that are active and belong to that group beside owners
            userList = _dbContext.Users
            .Where(g => g.Users_Groups
            .Any(ug => ug.groups_group_id == groupId && ug.role != "owner" && ug.status == "active"))
            .ToList();
        }

        public IActionResult OnPostDelete()
        {
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            List<string> validationErrors = new List<string>();
            //Check if task exists in group
            if (_dbContext.Tasks.Count(t => t.task_id == createOrEditTask.task_id && t.groups_group_id == groupId) == 0)
            {
                validationErrors.Add("Podane zadanie nie isnieje w tej grupie");
                return new JsonResult(validationErrors);
            }

            _dbContext.Remove(createOrEditTask);
            _dbContext.SaveChanges();
            return new JsonResult("success");
        }

        public IActionResult OnPostAdd()
        {
            //Reset the value of the error and get session values
            error = "";
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            List<string> validationErrors = new List<string>();

            if (!ModelState.IsValid)
            {
                var modelStateValidationErrors = ModelState.ToDictionary(ms => ms.Key,
                   ms => ms.Value.Errors.Select(e => e.ErrorMessage).ToList());

                return new JsonResult(modelStateValidationErrors);
            }

            error = TaskValidation.IsTaskValid(createOrEditTask.task_name, createOrEditTask.status, createOrEditTask.priority, createOrEditTask.description);
            if (error != "")
            {
                validationErrors.Add(error);
                return new JsonResult(validationErrors);
            }

            //Get list of actve users in the group
            userList = _dbContext.Users
                        .Where(g => g.Users_Groups
                        .Any(ug => ug.groups_group_id == groupId && ug.role != "owner" && ug.status == "active"))
                        .ToList();

            //Check if selected user is on the list of users in the group
            if (userList.Where(ul => ul.user_id == createOrEditTask.users_user_id).Count() == 0)
            {
                //If there is no such a user in the group
                validationErrors.Add("Nie istnieje w grupie użytkownik o podanych danych");
                return new JsonResult(validationErrors);
            }
            //Check if start date is lower than end date
            string isDateCorrect = IsEndDateHigherThanStartDate(createOrEditTask.start_date, createOrEditTask.end_date);
            if (isDateCorrect != "")
            {
                validationErrors.Add(isDateCorrect);
                return new JsonResult(validationErrors);
            }

            //Check if task is set to complete if so set finish_date
            if (createOrEditTask.status == "ukończone")
            {
                //Setting a date on now and setting seconds to 0
                createOrEditTask.finish_date = DateTime.Now.AddSeconds(-DateTime.Now.Second);
            }

            createOrEditTask.groups_group_id = (int)groupId;
            _dbContext.Tasks.Add(createOrEditTask);
            _dbContext.SaveChanges();
            return new JsonResult("success");
        }

        public IActionResult OnPostEdit()
        {
            //Reset the value of the error and get session values
            error = "";
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            List<string> validationErrors = new List<string>();

            //Check if task exists in group
            if (_dbContext.Tasks.Count(t => t.task_id == createOrEditTask.task_id && t.groups_group_id == groupId) == 0)
            {
                validationErrors.Add("Podane zadanie nie isnieje w tej grupie");
                return new JsonResult(validationErrors);
            }

            //Check if task is completed
            if (_dbContext.Tasks.Count(t => t.task_id == createOrEditTask.task_id && t.status == "ukończone") > 0)
            {
                validationErrors.Add("Podane zadanie jest już ukończone i nie podlega modyfikacji");
                return new JsonResult(validationErrors);
            }

            //Check if ModelState of send data is valid
            if (!ModelState.IsValid)
            {
                var modelStateValidationErrors = ModelState.ToDictionary(ms => ms.Key,
                   ms => ms.Value.Errors.Select(e => e.ErrorMessage).ToList());

                return new JsonResult(modelStateValidationErrors);
            }

            //Get list of actve users in the group
            userList = _dbContext.Users
                        .Where(g => g.Users_Groups
                        .Any(ug => ug.groups_group_id == groupId && ug.users_user_id != userId && ug.status == "active"))
                        .ToList();

            //If selected user is not on the list of users in the group
            if (userList.Where(ul => ul.user_id == createOrEditTask.users_user_id).Count() == 0)
            {
                validationErrors.Add("Nie istnieje w grupie użytkownik o podanych danych");
                return new JsonResult(validationErrors);
            }

            //If we are here then task exists and is in that group so now we check formating
            error = TaskValidation.IsTaskValid(createOrEditTask.task_name, createOrEditTask.status, createOrEditTask.priority, createOrEditTask.description);
            if (error != "")
            {
                validationErrors.Add(error);
                return new JsonResult(validationErrors);
            }

            //Check if start date is lower than end date
            string isDateCorrect = IsEndDateHigherThanStartDate(createOrEditTask.start_date, createOrEditTask.end_date);
            if (isDateCorrect != "")
            {
                validationErrors.Add(isDateCorrect);
                return new JsonResult(validationErrors);
            }

            //If nothing got returned to this point that means that it validated correctly
            EditTask(createOrEditTask);

Aplikacja webowa do zarządzania zespołami/Pages/Calendar.cshtml.cs
using Aplikacja_webowa_do_zarządzania_zespołami.Models;
using Aplikacja_webowa_do_zarządzania_zespołami.DTO_models_and_static_vars;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Data;
using Aplikacja_webowa_do_zarządzania_zespołami.DAO;

namespace Aplikacja_webowa_do_zarządzania_zespołami.Pages
{
    public class CalendarModel : PageModel
    {
        private readonly ITaskDAO _taskDAO;

        public CalendarModel(ITaskDAO taskDAO)
        {
            _taskDAO = taskDAO;
            tasksList = new List<Models.Task>();
        }

        public List<Models.Task> tasksList;
        public string data;
        public int? userId;
        public int? groupId;
        public string? username;


        //OnGet and OnPost methods
        public void OnGet()
        {
            data = HttpContext.Session.GetString(ConstVariables.GetKeyValue(1));
            username = HttpContext.Session.GetString(ConstVariables.GetKeyValue(4));
        }

        //Async methods
        public async Task<JsonResult> OnGetEventsAsync()
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            List<CalendarEventsDTO> events = await _taskDAO.GetCalendarEventsAsync(userId, groupId);

            return new JsonResult(events);
        }

        public async Task<JsonResult> OnGetTaskJsonAsync(int id)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            return new JsonResult(await _taskDAO.GetTaskAsync(id, userId, groupId));
        }
    }
}

Aplikacja webowa do zarządzania zespołami/Pages/PasswordRecovery.cshtml.cs
using Aplikacja_webowa_do_zarządzania_zespołami.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;
using System.Net;
using System.Web;
using System.Text;
using Aplikacja_webowa_do_zarządzania_zespołami.Validation;
using Aplikacja_webowa_do_zarządzania_zespołami.DAO;

namespace Aplikacja_webowa_do_zarządzania_zespołami.Pages
{
    public class PasswordRecoveryModel : PageModel
    {
        private readonly IUserDAO _userDAO;

        public PasswordRecoveryModel(IUserDAO userDAO)
        {
            _userDAO = userDAO;
        }

        [BindProperty]
        public string email { get; set; }

        private string PasswordGenerator(int howLong)
        {
            //Using string builder cause it is much faster that appending to string
            const string characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder password = new StringBuilder();
            Random pickNumber = new Random();
            for(int i = 0; i < howLong; i++)
            {
                password.Append(characters[pickNumber.Next(characters.Length)]);
            }
            return password.ToString();
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostRecover()
        {
            List<string> validationErrors = new List<string>();

            if(!_userDAO.IsAccountWithEmail(email))
            {
                validationErrors.Add("Nie istnieje konto powiązane z tym adresem e-mail");
                return new JsonResult(validationErrors);
            }

            string newPassword = PasswordGenerator(16);

            SmtpClient client = new SmtpClient();
            
            client.Host = "smtp.gmail.com";
            client.Port = 587;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = false;
            client.EnableSsl = true;
            client.Credentials = new NetworkCredential("AWDZZmail@gmail.com", "asrtmkwbqrevtmaj");

            MailMessage message = new MailMessage(
                from: new MailAddress("AWDZZmail@gmail.com", "AWDZZ"),
                to: new MailAddress(email, "Odbirca")
                );

            message.Subject = "Nowe hasło do aplikacji AWDZZ";
            message.Body = "Oto twoje nowe hasło:\n" + newPassword + "\n\nHasło możesz zmienić w menu profile w aplikacji";
            try
            {
                client.Send(message);
            }
            catch
            {
                validationErrors.Add("Wystąpił błąd spróbuj ponowinie później");
                return new JsonResult(validationErrors);
            }

            //If we are here that means that message was send
            _userDAO.SetNewPasswordEmail(email, newPassword);
            return new JsonResult("success");
        }

    }
}

Aplikacja webowa do zarządzania zespołami/Pages/Logout.cshtml
@page
@model Aplikacja_webowa_do_zarządzania_zespołami.Pages.LogoutModel
@{
}

Aplikacja webowa do zarządzania zespołami/Pages/OwnerNotices.cshtml
@page
@model Aplikacja_webowa_do_zarządzania_zespołami.Pages.OwnerNoticesModel
@{
    Layout = "_ComunicationLayout";
}
@if (Model.data != "Owner")
{
    Response.Redirect("/");
}

<div class="w-100 h-100 d-inline-block overflow-auto bg-main">
    <div class="p-4">
        <h1 class="text-center display-6 fw-bold">Tablica ogłoszeń</h1>
    </div>

    <div class="p-3">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card bg-table">
                        <div class="card-body">
                            <button class="btn float-end" data-bs-toggle="modal" data-bs-target="#add-notice-modal">
                                <i class="bi bi-plus-square"></i>
                                </button>
                            <div class="container mt-5">
                                <div class="row" id="noticeContainer">
                                    <partial name="Partials/_PartialNoticesView" model="Model.noticesList" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Edit and delete modal-->
<div class="modal fade" id="notice-modal">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <form method="post" id="deleteEditForm">
                <div class="modal-header">
                    <h3 id="topicText"></h3>
                </div>
                <div class="modal-body mt-2">
                    <div class="contain">
                        <div class="row">
                            <div class="col-md-6">
                                <p class="text-white" id="sender"></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-white" id="sendDate"></p>
                            </div>
                        </div>
                    </div>

                    <div class="contain mt-2 mb-5">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="form-label text-white-50" for="topic">Temat</label>
                                <hr />
                                <input type="text" id="topic" class="form-control text-light bg-dark" asp-for="notice.topic" />
                                <span asp-validation-for="notice.topic" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <p class="text-white-50">Wiadomość</p>
                    <hr />
                    <div class="mb-5">
                        <textarea class="wrap-text form-control" id="content" rows="8" asp-for="notice.content"></textarea>
                        <span asp-validation-for="notice.content" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
                    <button type="button" class="btn btn-danger" id="deleteBtn">Usuń</button>
                    <input type="hidden" asp-for="notice.message_id" id="update" />
                    <button type="button" class="btn btn-primary" id="editBtn">Edytuj</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Create modal -->
<div class="modal fade" id="add-notice-modal">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <form method="post" asp-page-handler="Add" id="addForm">
                <div class="modal-header">
                    <h3>Dodaj ogłoszenie</h3>
                </div>
                <div class="modal-body mt-2">
                    <div class="contain mt-2 mb-5">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="form-label text-white-50" for="topic">Temat</label>
                                <hr />
                                <input type="text" class="form-control text-light bg-dark" asp-for="notice.topic" />
                                <span asp-validation-for="notice.topic" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <p class="text-white-50">Wiadomość</p>
                    <hr />
                    <div class="mb-5">
                        <textarea class="wrap-text form-control" rows="8" asp-for="notice.content"></textarea>
                        <span asp-validation-for="notice.content" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
                    <button type="button" class="btn btn-primary" id="addBtn">Dodaj</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {

            $("#addBtn").click(function () {
                $("#addForm").submit();
            });

            //Changing form action to edit
            $("#editBtn").click(function () {
                $("#deleteEditForm").attr("action", "/OwnerNotices?handler=Edit");
                $("#deleteEditForm").submit();
            });

            //Changing form action to delete
            $("#deleteBtn").click(function () {
                $("#deleteEditForm").attr("action", "/OwnerNotices?handler=Delete");
                $("#deleteEditForm").submit();
            });

            //Cleaning function on modal call and submit
            $("form").on("submit", function () {
                $('span[data-valmsg-for]').text("");
            });

            $("#notice-modal").on("show.bs.modal", function () {
                $('span[data-valmsg-for]').text("");
            });

            $("#add-notice-modal").on("show.bs.modal", function () {
                $("span[data-valmsg-for]").text("");
            });

            //Get values to modal on click
            $("#noticeContainer").on("click", ".item", function () {
                //Wyświetl modal
                let idValue = $(this).attr("id");

                $.getJSON(`/OwnerNotices?handler=NoticeJson&id=${idValue}`).done(function (notice) {
                    $("#topicText").text(notice.topic);
                    $("#topic").val(notice.topic);
                    $("#content").text(notice.content);
                    $("#update").val(notice.message_id);
                    $("#sender").text("Od: " + notice.sender_name);
                    $("#sendDate").text("Zamieszczono: " + notice.send_date.replace("T", " "));
                });

                $("#notice-modal").modal("show");
            });

            //Form handling method
            $("form").submit(function (event) {
                event.preventDefault();

                let form = $(this);
                let actionUrl = form.attr("action");

                $.ajax({
                    type: form.attr("method"),
                    url: actionUrl,
                    data: form.serialize(),
                    dataType: "json",
                    success: function (data) {
                        if (Object.keys(data).length > 0 && !Array.isArray(data) && data != "success") {
                            let keys = Object.keys(data);

                            for (let i = 0; i < keys.length; i++) {
                                let key = keys[i];
                                let errors = data[key];
                                let errorSpan = $(`span[data-valmsg-for="${key}"]`);

                                if (errorSpan.length > 0) {
                                    errorSpan.text(errors[0]);
                                }
                            }
                        } else if (Array.isArray(data) && data.length > 0) {
                            let nameValidationError = $(`span[data-valmsg-for="notice.content"]`);
                            nameValidationError.text(data[0]);
                        }
                        else {
                            //Close modals
                            $("#notice-modal").modal("hide");
                            $("#add-notice-modal").modal("hide");

                            if ($("#noticeContainer").children().length > 0) {
                                $("#noticeContainer").empty();
                            }

                            $.ajax({
                                type: 'get',
                                url: '@Url.Page("OwnerNotices", "LoadNotices")',
                                success: function (partialResult) {
                                    $("#noticeContainer").append(partialResult);
                                }
                            });
                        }
                    }
                });
            });
        });
    </script>
}

Aplikacja webowa do zarządzania zespołami/Pages/PasswordRecovery.cshtml
@page "/PasswordRecovery"
@model Aplikacja_webowa_do_zarządzania_zespołami.Pages.PasswordRecoveryModel
@{
    Layout = "_LoginLayout";
}

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-5">

                            <form method="post" asp-page-handler="Recover">
                                <h2 class="fw-bold mb-2 text-uppercase">Odzyskaj hasło</h2>
                                <p class="text-white-50 mb-5">Proszę podać swój adres e-mail powiązany z kontem</p>

                                <div class="form-outline form-white mb-4">
                                    <input type="email" id="typeEmailX" class="form-control form-control-lg input-background" asp-for="email" />
                                    <span asp-validation-for="email" class="text-danger"></span>
                                </div>

                                <input class="btn btn-outline-primary btn-lg px-5 mt-3" type="submit" value="Odzyskaj hasło" />
                            </form>
                        </div>

                        <div>
                            <p class="small pb-lg-2"><a class="text-white-50" asp-area="" asp-page="/Login">Powrót do logowania</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Successfull recovery modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="success-modal">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container">
                    <div class="mb-3 mt-3">
                        <h3>Wysłano wiadomość na wskazany adres</h3>
                    </div>
                </div>
                <hr />
                <div class="text-end mb-3">
                    <button type="button" class="btn btn-secondary px-5 me-2" data-bs-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {

            $("form").submit(function (event) {
                event.preventDefault();

                let form = $(this);
                let actionUrl = form.attr("action");


                $.ajax({
                    type: form.attr("method"),
                    url: actionUrl,
                    data: form.serialize(),
                    dataType: "json",
                    success: function (data) {
                        if (Array.isArray(data) && data.length > 0) {
                            let nameValidationError = $(`span[data-valmsg-for="email"]`);
                            nameValidationError.text(data[0]);
                        }
                        else {
                            $("#success-modal").modal("show");
                            $("span[data-valmsg-for]").text("");
                        }
                    }
                });
            });
        });
    </script>
}