Aplikacja webowa do zarządzania zespołami/Pages/Messages.cshtml.cs
using Aplikacja_webowa_do_zarządzania_zespołami.Models;
using Aplikacja_webowa_do_zarządzania_zespołami.DTO_models_and_static_vars;
using Aplikacja_webowa_do_zarządzania_zespołami.PartialModels;
using Aplikacja_webowa_do_zarządzania_zespołami.Validation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Aplikacja_webowa_do_zarządzania_zespołami.DAO;

namespace Aplikacja_webowa_do_zarządzania_zespołami.Pages
{
    public class MessagesModel : PageModel
    {
        private readonly IMessageDAO _messageDAO;
        private readonly IUserDAO _userDAO;
        public MessagesModel(IMessageDAO messageDAO, IUserDAO userDAO)
        {
            _messageDAO = messageDAO;
            _userDAO = userDAO;
            reciveMessagesList = new List<ReciveMessagePartial>();
            sendedMessagesList = new List<SendedMessagePartial>();
            createMessagesPartial = new CreateMessagePartial();
            message = new Message();
        }

        public List<ReciveMessagePartial> reciveMessagesList;
        public List<SendedMessagePartial> sendedMessagesList;
        public Message message;
        public string data;
        public int? userId;
        public int? groupId;
        public string? username;

        [BindProperty(SupportsGet = true)]
        public CreateMessagePartial createMessagesPartial { get; set; }


        //OnGet and OnPost methods
        public void OnGet()
        {
            data = HttpContext.Session.GetString(ConstVariables.GetKeyValue(1));
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            username = HttpContext.Session.GetString(ConstVariables.GetKeyValue(4));

            //Check if user didn't deleted session (it causes function to throw exeptions
            try
            {
                reciveMessagesList = _messageDAO.GetRecivedMessages(10, 0, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }
        }

        public IActionResult OnPostCreate()
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            List<string> validationErrors = new List<string>();

            if (!ModelState.IsValid)
            {
                var modelStateValidationErrors = ModelState.ToDictionary(ms => ms.Key,
                   ms => ms.Value.Errors.Select(e => e.ErrorMessage).ToList());

                return new JsonResult(modelStateValidationErrors);
            }

            if (createMessagesPartial.messageUsers == "" || createMessagesPartial.messageUsers == null)
            {
                validationErrors.Add("Nie podano poprawnego odbiorcy");
                return new JsonResult(validationErrors);
            }

            //Parse value from hidden input (selectize)
            string[] reciversArray = createMessagesPartial.messageUsers.Split(',');
            List<int> reciversList = new List<int>();

            foreach (string reciver in reciversArray)
            {
                if (int.TryParse(reciver, out int parsedReciver))
                {
                    reciversList.Add(parsedReciver);
                }
                else
                {
                    validationErrors.Add("Nie znaleziono odbiorcy");
                    return new JsonResult(validationErrors);
                }
            }

            List<int> usersIdList = _userDAO.GetIdOfActiveUsersInGroup(userId, groupId);

            //Check if values on the list are valid users from that group
            foreach (int receiverId in reciversList)
            {
                if (!usersIdList.Contains(receiverId))
                {
                    validationErrors.Add("Nie znaleziono odbiorcy");
                    return new JsonResult(validationErrors);
                }
            }

            //If we are here that means that passed recivers are correct and are in the group
            string error = MessageValidation.IsMessageValid(createMessagesPartial.message.topic);
            if (error != "")
            {
                validationErrors.Add(error);
                return new JsonResult(validationErrors);
            }

            //At this point everything is correct so we can create a message
            _messageDAO.CreateMessage(createMessagesPartial.message, reciversList, (int)userId, (int)groupId);
            return new JsonResult("success");
        }

        //Partial methods
        public PartialViewResult OnGetReciveMessagesPartial(int howMany, int fromRecord)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            try
            {
                reciveMessagesList = _messageDAO.GetRecivedMessages(howMany, fromRecord, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }

            return Partial("Partials/_PartialReciveMessagesView", reciveMessagesList);
        }

        public PartialViewResult OnGetReciveSearchMessagesPartial(string condition)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            try
            {
                reciveMessagesList = _messageDAO.GetRecivedSearchMessages(condition, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }

            return Partial("Partials/_PartialReciveMessagesView", reciveMessagesList);
        }

        public PartialViewResult OnGetReciveMessage(int id)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            try
            {
                message = _messageDAO.GetRecivedMessageContent(id, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }
            return Partial("Partials/_PartialReciveMessage", message);
        }

        public PartialViewResult OnGetSendedMessagesPartial(int howMany, int fromRecord)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            //Get list of messages and nickname of one person that recived it (Group by and select statment)
            try
            {
                sendedMessagesList = _messageDAO.GetSendedMessages(howMany, fromRecord, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }


            return Partial("Partials/_PartialSendedMessagesView", sendedMessagesList);
        }

        public PartialViewResult OnGetSendedSearchMessagesPartial(string condition)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            //Get list of messages and nickname of one person that recived it (Group by and select statment)
            try
            {
                sendedMessagesList = _messageDAO.GetSendedSearchMessages(condition, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }


            return Partial("Partials/_PartialSendedMessagesView", sendedMessagesList);
        }

        public PartialViewResult OnGetSendedMessage(int id)
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));
            try
            {
                sendedMessagesList = _messageDAO.GetSendedMessageContent(id, (int)userId, (int)groupId);
            }
            catch
            {
                Page();
            }

            return Partial("Partials/_PartialSendedMessage", sendedMessagesList);
        }

        public PartialViewResult OnGetCreateMessage()
        {
            userId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(2));
            groupId = HttpContext.Session.GetInt32(ConstVariables.GetKeyValue(3));

            createMessagesPartial.usersList = _userDAO.GetActiveUsersInGroupBesidesYourself(userId, groupId);

            return Partial("Partials/_PartialCreateMessage", createMessagesPartial);
        }
    }
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialActiveUsers.cshtml
@model List<Models.User>

@if (!Model.Any())
{
    <div class="no-data">
        <p>Brak wyników</p>
    </div>
}
else
{
    <table class="table table-borderless mt-2">
        <thead>
            <tr>
                <th scope="col" class="col-md-3">Nazwa użytkownika</th>
                <th scope="col" class="col-md-3">Adres e-mail</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-id="@item.user_id" data-bs-toggle="modal" data-bs-target="#manage-user-modal">
                    <td>
                        @item.username

                        @if (item.name != null && item.surname != null)
                        {
                            @($"({item.name} {item.surname})")
                        }
                        else if (item.name != null)
                        {
                            @($"({item.name})")
                        }
                        else if (item.surname != null)
                        {
                            @($"({item.surname})")
                        }
                    </td>
                    <td>@item.e_mail</td>
                </tr>
            }
        </tbody>
    </table>
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialCreateMessage.cshtml
@model PartialModels.CreateMessagePartial
<form method="post" asp-page-handler="Create">
    <div class="mt-md-4 pb-5 pt-2 px-3">

        <div class="contain mb-4">
            <div class="row">
                <div class="col-md-5">
                    <label class="form-label" for="message-topic">Temat</label>
                    <br />
                    <input type="text" class="status-input form-control bg-dark" id="message-topic" asp-for="message.topic">
                    <span asp-validation-for="message.topic" class="text-danger"></span>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-5">
                    <label class="form-label" for="message">Odbiorca</label>
                    <br />
                    <select id="message" multiple="multiple">
                        @foreach (var item in Model.usersList)
                        {
                            <option value="@item.user_id">
                                @item.username

                                @if (item.name != null && item.surname != null)
                                {
                                    @($"({item.name} {item.surname})")
                                }
                                else if (item.name != null)
                                {
                                    @($"({item.name})")
                                }
                                else if (item.surname != null)
                                {
                                    @($"({item.surname})")
                                }
                            </option>
                        }
                    </select>
                    <input type="hidden" asp-for="messageUsers" id="message-user-hidden" />
                </div>
            </div>
        </div>

        <div class="mb-4">
            <label class="form-label" for="message-content">Treść wiadomości</label>
            <br />
            <textarea class="status-input form-control bg-dark" id="message-content" rows="8" asp-for="message.content"></textarea>
            <span asp-validation-for="message.content" class="text-danger"></span>
        </div>
        <input class="btn btn-primary" id="submitButton" type="submit" value="Wyślij wiadomość" />
    </div>
</form>

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialGroupsQuit.cshtml
@model List<PartialModels.GroupQuitPartial>

@if (!Model.Any())
{
    <div class="no-data">
        <p>Brak wyników</p>
    </div>
}
else
{
    <table class="table table-borderless">
        <thead>
            <tr>
                <th scope="col" class="col-md-3">Nazwa grupy</th>
                <th scope="col" class="col-md-2">Właściciel</th>
                <th scope="col" class="col-md-2">Twoja rola</th>
                <th scope="col" class="col-md-5">Opis</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-id="@item.group_id" data-bs-toggle="modal" data-bs-target="#quit-modal">
                    <td>@item.name</td>
                    <td>@item.owner_name</td>
                    <!-- Translation from db -->
                    @if (item.role == "owner")
                    {
                        <td>Właściciel</td>
                    }
                    @if (item.role == "user")
                    {
                        <td>Użytkownik</td>
                    }
                    <!-- Seting limits on description -->
                    @if (item.description.Length > 50)
                    {
                        <td>@item.description.Substring(0, 50)<span>...</span></td>
                    }
                    else
                    {
                        <td>@item.description</td>
                    }
                </tr>
            }
        </tbody>
    </table>
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialMessagesView.cshtml
@model List<MessagesModel.MessageView>
<hr/>
@foreach(var item in Model){
    <div class="item card-body" id="@item.message_id">
        <div class="contain">
            <div class="row">
                <div class="col-md-2">
                    Od: @item.sender_name
                </div>
                <div class="col-md-7">
                    Temat: @item.topic
                </div>
                <div class="col-md-3">
                    Data wysłania: @item.send_date
                </div>
            </div>
        </div>
    </div>
    <hr />
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialNoticesView.cshtml
@model List<PartialModels.NoticePartial>

@if (!Model.Any())
{
    <div class="no-data">
        <p class="mb-5">Brak wyników</p>
    </div>
}else
{
    @foreach (var item in Model)
    {
    <div class="col-md-4 mb-5 item" id="@item.message_id">
        <div class="card h-100 mb-4">
            <div class="card-header">
                <h2>@item.topic</h2>
                <p>Od: @item.sender_name</p>
                <p>Zamieszczono: @item.send_date</p>
            </div>
            <div class="card-body wrap-text">
                    @if (item.content.Length > 200)
                    {
                        <div>@item.content.Substring(0, 200)<span>...</span></div>
                    }
                    else
                    {
                        <div>@item.content</div>
                    }
            </div>
        </div>
    </div>
    }
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialOwnerTask.cshtml
@model List<Models.Task>

<table id="DataTable" class="dataTable table table-borderless">
    <thead>
        <tr>
            <th scope="col">Nazwa zadania</th>
            <th scope="col">Data zadania</th>
            <th scope="col">Data wykonania</th>
            <th scope="col">Status</th>
            <th scope="col">Stopień ważności</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@item.task_id" data-bs-toggle="modal" data-bs-target="#edit-modal">
                <td>@item.task_name</td>
                <td>@item.start_date</td>
                <td>@item.end_date</td>
                <td>@item.status</td>
                <td class="priority-table">@item.priority</td>
            </tr>
        }
    </tbody>
</table>

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialOwnerTasks.cshtml
@model List<PartialModels.OwnerTaskPartial>

@if (!Model.Any())
{
    <div class="no-data-task-add-btn">
        <button class='btn btn-primary ms-2' data-bs-toggle='modal' data-bs-target='#create-modal' id='addButton'>Dodaj zadanie</button>
    </div>
    <div class="no-data">
        <p>Brak wyników</p>
    </div>
}
else
{
    <table id="DataTable" class="dataTable table table-borderless">
        <thead>
            <tr>
                <th scope="col">Nazwa zadania</th>
                <th scope="col">Data zadania</th>
                <th scope="col">Data wykonania</th>
                <th scope="col">Status</th>
                <th scope="col">Stopień ważności</th>
                <th scope="col">Wykonawca</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="dataTable-hover-tr" data-id="@item.task_id" data-bs-toggle="modal" data-bs-target="#edit-modal">
                    <td>@item.task_name</td>
                    <td>@item.start_date.ToString("yyyy-MM-dd HH:mm")</td>
                    <td>@item.end_date.ToString("yyyy-MM-dd HH:mm")</td>
                    <td>@item.status</td>
                    <td class="priority-table">@item.priority</td>
                    <td>@item.username</td>
                </tr>
            }
        </tbody>
    </table>
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialPendingUsers.cshtml
@model List<Models.User>

@if (!Model.Any())
{
    <div class="no-data">
        <p>Brak wyników</p>
    </div>
}
else
{
    <table class="table table-borderless mt-2">
        <thead>
            <tr>
                <th scope="col" class="col-md-3">Nazwa użytkownika</th>
                <th scope="col" class="col-md-3">Adres e-mail</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-id="@item.user_id" data-bs-toggle="modal" data-bs-target="#accept-pending-user-modal">
                    <td>
                        @item.username

                        @if (item.name != null && item.surname != null)
                        {
                            @($"({item.name} {item.surname})")
                        }
                        else if (item.name != null)
                        {
                            @($"({item.name})")
                        }
                        else if (item.surname != null)
                        {
                            @($"({item.surname})")
                        }
                    </td>
                    <td>@item.e_mail</td>
                </tr>
            }
        </tbody>
    </table>
}

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialQuitGroup.cshtml
@model List<JoinGroupModel.GroupQuitDTO>

<table class="table table-borderless">
    <thead>
        <tr>
            <th scope="col" class="col-md-3">Nazwa grupy</th>
            <th scope="col" class="col-md-2">Właściciel</th>
            <th scope="col" class="col-md-2">Twoja rola</th>
            <th scope="col" class="col-md-5">Opis</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@item.group_id" data-bs-toggle="modal" data-bs-target="#quit-modal">
                <td>@item.name</td>
                <td>@item.owner_name</td>
                <!-- Translation from db -->
                @if (item.role == "owner")
                {
                    <td>Właściciel</td>
                }
                @if (item.role == "user")
                {
                    <td>Użytkownik</td>
                }
                <!-- Seting limits on description -->
                @if (item.description.Length > 50)
                {
                    <td>@item.description.Substring(0, 50)<span>...</span></td>
                }
                else
                {
                    <td>@item.description</td>
                }
            </tr>
        }
    </tbody>
</table>

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialSendedMessage.cshtml
@model List<PartialModels.SendedMessagePartial>

<div class="form-control mt-5">
    <p class="pb-5 pt-3" style="color:rgba(255,255,255,.75)"> Wszyscy odbiorcy: 
        @string.Join(", ", Model.Select(item => item.reciver_name))
    </p>
    <p class="text-white-50">Wiadomość</p>
    <hr />
    <div class="pb-5 wrap-text" style="color:rgba(255,255,255,.75)">@Model[0].content</div>
</div>

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialUserAccountData.cshtml
@model PartialModels.UserAccountDataPartial
<div class="mb-md-5 mt-md-4 pb-5">

    <form method="post" id="accountForm" asp-page-handler="AccountDataEdit">
        <div class="contain">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-7 form-outline form-white mb-4">
                    <div class="mb-4">
                        <label class="form-label" for="oldPassword">Stare hasło</label><br />
                        <input type="password" id="oldPassword" class="form-control form-control-lg text-light input-background" asp-for="oldPassword" />
                        <span asp-validation-for="oldPassword" class="text-danger"></span>
                    </div>
                    <div class="mb-4">
                        <label class="form-label" for="newPassword">Nowe hasło</label><br />
                        <input type="password" id="newPassword" class="form-control form-control-lg text-light input-background" asp-for="newPassword" />
                        <span asp-validation-for="newPassword" class="text-danger"></span>
                        </div>
                    <div class="mb-4">
                        <label class="form-label" for="newPasswordRepeat">Powtórz hasło</label><br />
                        <input type="password" id="newPasswordRepeat" class="form-control form-control-lg text-light input-background" asp-for="newPasswordRepeat" />
                        <span asp-validation-for="newPasswordRepeat" class="text-danger"></span>
                    </div>

                    <div class="d-flex justify-content-end mb-3">
                        <button class="btn btn-primary">Zatwierdź zmiany</button>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </form>
</div>

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialUserPersonalData.cshtml
@model PartialModels.UserPersonalDataPartial
<div class="mb-md-5 mt-md-4 pb-5">

    <form method="post" id="personalForm" asp-page-handler="PersonalDataEdit">
        <div class="contain">
            <div class="row">
                <div class="col-md-6 form-outline form-white mb-4">
                    <label class="form-label" for="name">Imie*</label><br />
                    <input type="text" id="name" class="form-control form-control-lg text-light input-background" asp-for="name" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>

                <div class="col-md-6 form-outline form-white mb-4">
                    <label class="form-label" for="surname">Nazwisko*</label><br />
                    <input type="text" id="surname" class="form-control form-control-lg text-light input-background" asp-for="surname" />
                    <span asp-validation-for="surname" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-outline form-white mb-4">
            <label class="form-label" for="username">Nazwa użytkownika</label><br />
            <input type="text" id="username" class="form-control form-control-lg text-light input-background" asp-for="username" />
            <span asp-validation-for="username" class="text-danger"></span>
        </div>

        <div class="d-flex justify-content-end mb-3">
            <button class="btn btn-primary">Zatwierdź zmiany</button>
        </div>
    </form>

    <hr/>
    <p class="text-white-50">* - opcjonalne</p>
</div>

Aplikacja webowa do zarządzania zespołami/Pages/Partials/_PartialUserTasks.cshtml
@model List<Models.Task>

@if (!Model.Any())
{
    <div class="no-data">
        <p>Brak wyników</p>
    </div>
}
else
{
    <table id="DataTable" class="dataTable table table-borderless">
        <thead>
            <tr>
                <th scope="col">Nazwa zadania</th>
                <th scope="col">Data zadania</th>
                <th scope="col">Data wykonania</th>
                <th scope="col">Status</th>
                <th scope="col">Stopień ważności</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="dataTable-hover-tr" data-id="@item.task_id" data-bs-toggle="modal" data-bs-target="#complete-modal">
                    <td>@item.task_name</td>
                    <td>@item.start_date.ToString("yyyy-MM-dd HH:mm")</td>
                    <td>@item.end_date.ToString("yyyy-MM-dd HH:mm")</td>
                    <td>@item.status</td>
                    <td class="priority-table">@item.priority</td>
                </tr>
            }
        </tbody>
    </table>
}